language : node_js
node_js :
 - stable
install:
 - yarn install
 - yarn build
 - yarn test
script:
 - yarn cover
# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"